name: aufmass_app
description: Aufmaß App fuer Handwerker
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  pdf: ^3.6.0
  flutter:
    sdk: flutter
  event: ^2.1.2
  meta: ^1.9.1
  flutter_spinkit: ^5.2.0
  collection: ^1.17.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/