name: aufmass_app
description: Aufmaß App fuer Handwerker
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  pdf: ^3.10.7
  flutter:
    sdk: flutter
  event: ^2.1.2
  meta: ^1.9.1
  flutter_spinkit: ^5.2.0
  collection: ^1.17.2
  dcdg: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  device_preview: ^1.1.0
  provider: ^6.1.1
  screenshot: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/